### ISSUE TITLE
AD_Column X-Class is outdated 

### ISSUE THREAD

**Issue by Benedikt1996** [VIENNA-Advantage-ERP-CRM/official-viennaadvantage-erp-crm#1]
There are a few Get/Set-methods missing in the Class "X_AD_Column". Please Generate a new one.
The Column I am missing is named "IsLink".
@erp-crm-viennaadvantage can you do this?

**Comment by erp-crm-viennaadvantage** [comment]
Hi Malocher,
Thanks for informing this issue. We have added all the missing columns in X_AD_Column. If you found any other issue please feel free to contact us.

**Comment by Benedikt1996** [comment]
Thank you very much!
